Update baseClient.ts
Classcharts-API/classcharts-api pull request #12
Opened 2022-03-28 12:36 UTC by timthedev07

New method

2022-03-28 21:00 UTC, jamesatjaminit requested changes

2022-03-28 21:00 UTC, jamesatjaminit commented on src/baseClient.ts
> +  async getFullActivity(from: string, to: string, client: ClasschartsClient) {
```suggestion
  async getFullActivity(options:getFullActivityOptions) {
```
I'd prefer it if we could use a object like the other functions

2022-03-28 21:00 UTC, jamesatjaminit commented on src/baseClient.ts
> +  async getFullActivity(from: string, to: string, client: ClasschartsClient) {
```suggestion
  async getFullActivity(from: string, to: string) {
```
The client shouldn't be needed here, see comment below

2022-03-28 21:00 UTC, jamesatjaminit commented on src/baseClient.ts
> +      const fragment = await client.getActivity(params);
```suggestion
      const fragment = await this.getActivity(params);
```
We can use the existing client

2022-03-28 21:00 UTC, jamesatjaminit commented
Thanks for this, an issue which has been on my mind for a while. Not sure whether the best place for it is in a function in itself or the existing function but this will do for now.

2022-04-01 10:40 UTC, timthedev07 commented
Thanks! I originally had a standalone function so that's why the first version didn't fit well into a class method.

2022-04-01 10:40 UTC, closed without merging

2022-04-02 11:15 UTC, jamesatjaminit commented
Implemented in https://github.com/Classcharts-API/classcharts-api/commit/eea157566c90f6ac609dfd7df9803f85294cc636