feat: add reward shop methods
Classcharts-API/classcharts-api pull request #35
Opened 2023-09-15 19:06 UTC by veloii

Added purchase and get methods for the student's reward shop.

2023-09-15 20:02 UTC, jamesatjaminit requested changes

2023-09-15 20:02 UTC, jamesatjaminit commented on src/core/baseClient.ts
> +  async getPupilFields(): Promise<PupilFieldsResponse> {
```suggestion
  async getCustomFields(): Promise<PupilFieldsResponse> {
```
I'm not familiar with this endpoint so this may not be worth changing, but judging by the API route, `getCustomFields` may be more clear?

2023-09-15 20:02 UTC, jamesatjaminit commented on src/core/baseClient.ts
> +  async postRewardPurchase(itemId: number): Promise<RewardPurchaseResponse> {
```suggestion
  async purchaseReward(itemId: number): Promise<RewardPurchaseResponse> {
```
Perhaps this method would be better named `purchaseReward`. Sorry if it was unclear but in the other methods get wasn't meaning the http method, it was simply a verb.

2023-09-15 20:02 UTC, jamesatjaminit commented on src/core/baseClient.ts
> +  PupilFieldsResponse,
```suggestion
  CustomFieldsResponse,
```
See other comment

2023-09-15 20:02 UTC, jamesatjaminit commented on src/core/baseClient.ts
> +        this.API_BASE + "/apiv2student/customfields" + this.studentId,
```suggestion
        this.API_BASE + "/apiv2student/customfields/" + this.studentId,
```
Missing forward slash

2023-09-15 20:02 UTC, jamesatjaminit commented on src/core/baseClient.ts
> +        this.API_BASE + "/purchase" + itemId,
```suggestion
        this.API_BASE + "/purchase/" + itemId,
```
Missing forward slash

2023-09-17 09:42 UTC, jamesatjaminit commented
Also, do you know whether these endpoints are accessible from the parent client? If not they should be moved to `studentClient.ts`.

2023-09-17 11:09 UTC, IsaacHatton commented
I know my parent app doesn't have the shop but student does, I don't know about the other two.

2023-09-18 16:57 UTC, veloii commented on src/core/baseClient.ts
> +  async getPupilFields(): Promise<PupilFieldsResponse> {
In ClassCharts it's shown as Pupil Fields, so it might be better to keep it to avoid confusion.

2023-09-18 16:59 UTC, jamesatjaminit commented on src/core/baseClient.ts
> +  async getPupilFields(): Promise<PupilFieldsResponse> {
Fair enough

2023-09-18 17:00 UTC, veloii commented
I've updated it so the reward shop is in the student client now.

2023-09-18 19:33 UTC, jamesatjaminit requested changes

2023-09-18 19:33 UTC, jamesatjaminit commented on src/core/studentClient.ts
> +   * Purchase a reward item from the current student's  rewards shop
```suggestion
   * Purchase a reward item from the current student's rewards shop
```

2023-09-18 19:33 UTC, jamesatjaminit commented on src/core/studentClient.ts
> +   * @returns An object containg balence and id
```suggestion
   * @returns An object containing the current student's balance and id
```

2023-09-18 19:33 UTC, jamesatjaminit commented on src/types.ts
> +  balence: number;
```suggestion
  balance: number;
```

2023-09-18 19:34 UTC, jamesatjaminit commented
Apologies for the small nitpicks, I would have committed them myself but git is being funky and not letting me. If you have deno installed, would you be able to run `deno fmt .` as well please :)

2023-09-18 19:45 UTC, veloii commented
Yes, no problem.

2023-09-18 19:46 UTC, merged